version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./postgres/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "som3thingS3cretForM3r00t"
  web:
    build: ./ruby-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db